<?php
return array(
	'BE' => array(
		'installToolPassword' => '$1$AitlcawC$tvqlNLrJx6xDfY99AlTTV.',
		'loginSecurityLevel' => 'rsa',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 'typo3',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => 'localhost',
		'password' => 'typo3',
		'socket' => '',
		'username' => 'typo3',
	),
	'EXT' => array(
		'extConf' => array(
			'coreapi' => 'a:0:{}',
			'helmbert_bootstrapsite' => 'a:0:{}',
			'phpunit' => 'a:7:{s:17:"excludeextensions";s:8:"lib, div";s:12:"composerpath";s:0:"";s:13:"selenium_host";s:9:"localhost";s:13:"selenium_port";s:4:"4444";s:16:"selenium_browser";s:8:"*firefox";s:19:"selenium_browserurl";s:0:"";s:10:"phpunitlib";s:0:"";}',
			'saltedpasswords' => 'a:2:{s:3:"FE.";a:2:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}s:3:"BE.";a:1:{s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}}',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'de',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'FE' => array(
		'loginSecurityLevel' => 'rsa',
	),
	'GFX' => array(
		'im_mask_temp_ext_gif' => 1,
	),
	'SYS' => array(
		'compat_version' => '6.1',
		'displayErrors' => '1',
		'encryptionKey' => '0f7619b0b530c7b43b6d2cbf7351778f64a71221935761a107eb9608e64e4825ab11b42e48eee6ca0f322c1c6f199ea6',
		'sitename' => 'TYPO3 CI demonstration site.',
	),
);
?>