language: php
php: [5.6, 5.5, 5.4]
env:
  - TYPO3_VERSION=TYPO3_6-2-15
matrix:
  exclude:
    - php: 5.4
      env: TYPO3_VERSION=TYPO3_7-6-0
    - php: 5.4
      env: TYPO3_VERSION=TYPO3_7-5-0

services: [mysql]
install:
  - composer install
  - mkdir ${TRAVIS_BUILD_DIR}/src/typo3_src-${TYPO3_VERSION} && cd ${TRAVIS_BUILD_DIR}/src/typo3_src-${TYPO3_VERSION} && wget https://github.com/TYPO3/TYPO3.CMS/archive/${TYPO3_VERSION}.tar.gz && tar --strip-components=1 -xzf ${TYPO3_VERSION}.tar.gz
  - ln -nfs ${TRAVIS_BUILD_DIR}/src/typo3_src-${TYPO3_VERSION} ${TRAVIS_BUILD_DIR}/src/typo3_src
  - composer install -d ${TRAVIS_BUILD_DIR}/src/typo3_src
before_script:
  - mysql -e 'CREATE DATABASE typo3;'
  - mysql typo3 < ${TRAVIS_BUILD_DIR}/provision/database.sql
script:
  - cd ${TRAVIS_BUILD_DIR}
  - bin/phing
